import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full`}>
      <body className="min-h-full">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
